POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "ndamore@example.net",
    "password": "password"
}
###
GET http://127.0.0.1:8000/api/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?page=2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?completed=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?title=dolor
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks?order=desc
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks?order=asc
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
POST http://127.0.0.1:8000/api/tasks/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

{
    "title": "Feed my cobayas",
    "completed": true
}
###
PUT http://127.0.0.1:8000/api/tasks/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
