POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "howell.thad@example.net",
    "password": "password"
}
###
GET http://127.0.0.1:8000/api/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|4DERzj4ezrLOlYYcFRimwqpi8UNTHHr7F7ZcMVJbef86545d
###
GET http://127.0.0.1:8000/api/tasks?page=2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?completed=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?title=dolor
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks?order=desc
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks?order=asc
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
POST http://127.0.0.1:8000/api/tasks/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

{
    "title": "Comprar pizzas",
    "completed": true
}
###
PUT http://127.0.0.1:8000/api/tasks/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/projects
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|4DERzj4ezrLOlYYcFRimwqpi8UNTHHr7F7ZcMVJbef86545d
###

GET http://127.0.0.1:8000/api/projects/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|4jMpS9cP6MUFZTLPQN68i3wP284UViCx1xd5Z7iD7acb9008
###

POST http://127.0.0.1:8000/api/projects
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|4DERzj4ezrLOlYYcFRimwqpi8UNTHHr7F7ZcMVJbef86545d

{
    "title": "My project"
}
###
