POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "zackary.pfannerstill@example.org",
    "password": "password"
}
###
GET http://127.0.0.1:8000/api/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|4DERzj4ezrLOlYYcFRimwqpi8UNTHHr7F7ZcMVJbef86545d
###
GET http://127.0.0.1:8000/api/tasks?page=2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?completed=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/tasks?title=dolor
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks?order=desc
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks?order=asc
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###

GET http://127.0.0.1:8000/api/tasks/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
POST http://127.0.0.1:8000/api/tasks/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

{
    "title": "Comprar pizzas",
    "completed": true
}
###
PUT http://127.0.0.1:8000/api/tasks/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}
###
GET http://127.0.0.1:8000/api/projects
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|EfqMZXMtrDvJMBLTOljv99yorlKQDtNnfTNhxZpU377f54b8
###

GET http://127.0.0.1:8000/api/projects/11
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|EfqMZXMtrDvJMBLTOljv99yorlKQDtNnfTNhxZpU377f54b8
###

POST http://127.0.0.1:8000/api/projects
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|EfqMZXMtrDvJMBLTOljv99yorlKQDtNnfTNhxZpU377f54b8

{
    "title": "My project"
}
###

DELETE http://127.0.0.1:8000/api/projects/11/remove-members
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|EfqMZXMtrDvJMBLTOljv99yorlKQDtNnfTNhxZpU377f54b8

{
    "user_ids": [1]
}
###
